FROM ghcr.io/astral-sh/uv:python3.13-trixie

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y sudo && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash ubuntu && \
    echo "ubuntu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/ubuntu && \
    chmod 0440 /etc/sudoers.d/ubuntu

USER ubuntu
WORKDIR /home/ubuntu